<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require __DIR__ . '/vendor/autoload.php';

$cache = __DIR__ . "/cache.json";

$data = json_decode(file_get_contents($cache), true);

if(empty($data['details'])){
    die("No data loaded from cache.json\n");
}

$month = $argv[1] ?? date("Y-m",strtotime("first day of last month"));

$csv="/tmp/print_report_$month.csv";

$users=[];
$printers=[];
$totalPages=0;
$totalJobs=0;


/*
CREATE CSV
*/

$f=fopen($csv,"w");

fputcsv($f,["Date","Time","Printer","User","IP","File","Pages"]);

foreach($data['details'] as $d){

    if(strpos($d['date'], $month) !== 0) continue;

    fputcsv($f,[
        $d['date'],
        $d['time'],
        $d['printer'],
        $d['user'],
        $d['ip'],
        $d['file'],
        $d['pages']
    ]);

    $totalJobs++;

    $totalPages += (int)$d['pages'];

    $users[$d['user']] = ($users[$d['user']] ?? 0) + (int)$d['pages'];

    $printers[$d['printer']] = ($printers[$d['printer']] ?? 0) + (int)$d['pages'];

}

fclose($f);


arsort($users);
arsort($printers);

$topUsers=array_slice($users,0,5,true);
$topPrinters=array_slice($printers,0,5,true);


/*
EMAIL BODY
*/

$body="";

$body.="Report month : $month\n";
$body.="Server       : ".gethostname()."\n";
$body.="Generated at : ".date("Y-m-d H:i:s")."\n\n";

$body.="SUMMARY\n";
$body.="-------------------------------------\n";
$body.="Total Jobs  : $totalJobs\n";
$body.="Total Pages : $totalPages\n\n";


$body.="TOP USERS\n";

foreach($topUsers as $u=>$p){

    $body.=sprintf("%-20s %s pages\n",$u,$p);

}

$body.="\nTOP PRINTERS\n";

foreach($topPrinters as $p=>$c){

    $body.=sprintf("%-20s %s pages\n",$p,$c);

}


/*
ADD DASHBOARD LINK
*/

$body.="\n-------------------------------------\n";
$body.="Dashboard realtime report: http://IP_Server/cups-report\n\n"; //edit here


$body.="\nThis is an automated report generated by the Infrastructure team. Please do not reply to this email!\n";


/*
SEND MAIL
*/

$mail = new PHPMailer(true);

try {

$mail->isSMTP();

$mail->Host       = 'smtp.office365.com';
$mail->SMTPAuth   = true;

$mail->Username   = 'your@email.com';
$mail->Password   = 'tqp'; //edit here

$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;

$mail->Port       = 587;


$mail->setFrom(
'your@email.com', //edit here
'CUPS Print System'
);


$to_list = "
your@email.com, 
your@group.com,
"; //edit here

$recipients = explode(',', $to_list);

foreach ($recipients as $email) {

$email=trim($email);

if($email)
$mail->addAddress($email);

}


$mail->isHTML(false);

$mail->Subject = "Print Report $month";

$mail->Body    = $body;

$mail->addAttachment($csv, basename($csv));

$mail->send();

echo "CSV report sent successfully for $month via SMTP!\n";

}

catch (Exception $e) {

echo "I don't send email. Detail: {$mail->ErrorInfo}\n";

}
