<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php';

$data=json_decode(file_get_contents("cache.json"),true);

$month = $argv[1] ?? date("Y-m",strtotime("first day of last month"));

$csv="/tmp/print_report_$month.csv";

$users=[];
$printers=[];
$totalPages=0;
$totalJobs=0;



/*
CREATE CSV
*/

$f=fopen($csv,"w");

fputcsv($f,["Date","Time","Printer","User","IP","File","Pages"]);

foreach($data['details'] as $d){

    if(substr($d['date'],0,7)!=$month) continue;

    fputcsv($f,[
        $d['date'],
        $d['time'],
        $d['printer'],
        $d['user'],
        $d['ip'],
        $d['file'],
        $d['pages']
    ]);

    $totalJobs++;

    $totalPages += $d['pages'];

    $users[$d['user']] = ($users[$d['user']] ?? 0) + $d['pages'];

    $printers[$d['printer']] = ($printers[$d['printer']] ?? 0) + $d['pages'];

}

fclose($f);



arsort($users);
arsort($printers);

$topUsers=array_slice($users,0,5,true);
$topPrinters=array_slice($printers,0,5,true);



/*
EMAIL BODY
*/

$body="Monthly Print Report\n";
$body.="-------------------------------------\n";

$body.="Report Month : $month\n";
$body.="Server       : ".gethostname()."\n";
$body.="Generated At : ".date("Y-m-d H:i:s")."\n\n";

$body.="SUMMARY\n";
$body.="-------------------------------------\n";
$body.="Total Jobs  : $totalJobs\n";
$body.="Total Pages : $totalPages\n\n";


$body.="TOP USERS\n";

foreach($topUsers as $u=>$p){

    $body.=sprintf("%-20s %s pages\n",$u,$p);

}

$body.="\nTOP PRINTERS\n";

foreach($topPrinters as $p=>$c){

    $body.=sprintf("%-20s %s pages\n",$p,$c);

}


/*
ADD DASHBOARD LINK
*/

$body.="\n-------------------------------------\n";
$body.="Dashboard Report Web\n";
$body.="http://"Your_IP_Server"/cups-report\n\n"; //edit here


$body.="Full report attached (CSV).\n";
$body.="\nThis is an automated report generated by the CUPS Print Monitoring System.\n";



/*
SEND MAIL
*/

$mail = new PHPMailer(true);

try {

$mail->isSMTP();

$mail->Host       = 'smtp.office365.com';
$mail->SMTPAuth   = true;

$mail->Username   = 'email_report@domain.vn'; //edit here
$mail->Password   = 'password_app'; //no using password default

$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;

$mail->Port       = 587;



$mail->setFrom(
'email_report@domain.vn', //edit here
'CUPS Print System'
);



$to_list = "
email1@domain.vn,
email2@domain.vn,
"; //edit here

$recipients = explode(',', $to_list);

foreach ($recipients as $email) {

$email=trim($email);

if($email)
$mail->addAddress($email);

}



$mail->isHTML(false);

$mail->Subject = "Print Report $month";

$mail->Body    = $body;



$mail->addAttachment($csv, basename($csv));



$mail->send();

echo "CSV report sent successfully for $month via SMTP!\n";

}

catch (Exception $e) {

echo "I don't sent email. Detail: {$mail->ErrorInfo}\n";

}
